### ISSUE TITLE
Filger standalone

### ISSUE THREAD

**Issue by brandalf88** [lua-wow/Filger#2]
Hi,
I use Fliger for many Years and i like it. Now i want to use it with the Retail UI. Is there any chance, to run Filger Standallone witout a UI Addon?

**Comment by Profilabs** [comment]
I second this =)

**Comment by pedrozc90** [comment]
Hello there!

I'm really sorry for taking so long to replay. It just came to my attention that somebody else is using my addon.
That's interesting. :astonished:

Damn... @Profilabs send a issue in 2020. :scream:

I've rewritten the Filger addon primarily for personal use, so I've made it dependent of Tukui, since I've been using it since 2014. If I'm not wrong.
I'll take a closer look at the request and make it standalone for you guys, no problem.

Thank you very much for posting the issues.

obs.: The branch `master` works for **Retail**, **Classic Era** and **Classic Wrath**, so you don't need to use the branch `classic`. I think branch `classic` is outdated too.

**Comment by brandalf88** [comment]
No Problem. The UI Interface Pack ShestakUI uses your package. I'll be very happy if you can actually do it standalone.

**Comment by pedrozc90** [comment]
I've made Tukui as optional dependency.
You can download the new version here  [v4.3.0](https://github.com/pedrozc90/Filger/releases/tag/v4.3.0)
